/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;

import AlbumnesPostalesLogica.Album;
import AlbumnesPostalesLogica.ListaAlbum;
import javax.swing.JOptionPane;
import javax.swing.*;
/**
 *
 * @author Cristian
 */
public class AlbumIG extends javax.swing.JFrame {

    /**
     * Creates new form AlbumIG
     */
    ListaAlbum la = new ListaAlbum();
    
    
    
    public AlbumIG() {
        initComponents();
        Album al = new Album( "mundial 1998", 1, 50);
        Album al1 = new Album( "mundial 2002", 2, 50);
        Album al2 = new Album( "mundial 2006", 3, 50);
        la.insertar(al);
        la.insertar(al1);
        la.insertar(al2);
        txtPrincipal.setText(la.mostrar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarAlbum = new javax.swing.JButton();
        btnAgregarPostal = new javax.swing.JButton();
        btnVenderPostal = new javax.swing.JButton();
        btnVerAlbum = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrincipal = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarAlbum.setBackground(new java.awt.Color(255, 105, 97));
        btnAgregarAlbum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarAlbum.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarAlbum.setText("Agregar Album");
        btnAgregarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlbumActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        btnAgregarPostal.setBackground(new java.awt.Color(255, 105, 97));
        btnAgregarPostal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarPostal.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPostal.setText("Agregar Postal");
        btnAgregarPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPostalActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        btnVenderPostal.setBackground(new java.awt.Color(255, 105, 97));
        btnVenderPostal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVenderPostal.setForeground(new java.awt.Color(255, 255, 255));
        btnVenderPostal.setText("Vender Postal");
        btnVenderPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderPostalActionPerformed(evt);
            }
        });
        getContentPane().add(btnVenderPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        btnVerAlbum.setBackground(new java.awt.Color(255, 105, 97));
        btnVerAlbum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVerAlbum.setForeground(new java.awt.Color(255, 255, 255));
        btnVerAlbum.setText("Ver Albumnes");
        btnVerAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAlbumActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        txtPrincipal.setEditable(false);
        txtPrincipal.setColumns(20);
        txtPrincipal.setRows(5);
        jScrollPane1.setViewportView(txtPrincipal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 340, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo-de-un-solo-color-sencillo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, -8, 720, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlbumActionPerformed
       String id_aS = JOptionPane.showInputDialog( "Digite el id del album:" );
       int id_a = Integer.parseInt(id_aS);
       String nombreAlbum = JOptionPane.showInputDialog ("Escribe el nombre del album:"); 
       String numPosS = JOptionPane.showInputDialog( "Digite el numero de postales del album:" );
       int nuPos = Integer.parseInt(numPosS);
       Album al = new Album( nombreAlbum, id_a, nuPos);
       la.insertar(al);
       txtPrincipal.setText(la.mostrar());
    }//GEN-LAST:event_btnAgregarAlbumActionPerformed

    private void btnAgregarPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPostalActionPerformed
        // TODO add your handling code here:
       String id_aS = JOptionPane.showInputDialog( "Digite el id del album, en el que desea agregar una postal:" );
       int id_a = Integer.parseInt(id_aS);
       String numPosS = JOptionPane.showInputDialog( "Digite el numero de postal que desea agregar:" );
       int nuPos = Integer.parseInt(numPosS);
       if(la.insertarPostal(id_a, nuPos) == true){
           JOptionPane.showMessageDialog(null, "La postal se agrego con exito");
       }
       else{
           JOptionPane.showMessageDialog(null, "El album no existe, o la postal es un numero invalido, intente de nuevo!!");
       }
       
       txtPrincipal.setText(la.mostrar());
    }//GEN-LAST:event_btnAgregarPostalActionPerformed

    private void btnVenderPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderPostalActionPerformed
        // TODO add your handling code here:
         String id_aS = JOptionPane.showInputDialog( "Digite el id del album, en el que desea vender una postal:" );
       int id_a = Integer.parseInt(id_aS);
       String numPosS = JOptionPane.showInputDialog( "Digite el numero de postal que desea vender:" );
       int nuPos = Integer.parseInt(numPosS);
       if(la.VenderPostal(id_a, nuPos) == true)
           JOptionPane.showMessageDialog(this, "La postal se vendio con exito!!");
       else
           JOptionPane.showMessageDialog(this, "El identificador del album es incorrecto, o no tienes esa postal repetida, intentalo de nuevo....");
       txtPrincipal.setText(la.mostrar());
    }//GEN-LAST:event_btnVenderPostalActionPerformed

    private void btnVerAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlbumActionPerformed
        // TODO add your handling code here:
        txtPrincipal.setText(la.mostrar());
    }//GEN-LAST:event_btnVerAlbumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlbumIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlbumIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlbumIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlbumIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlbumIG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlbum;
    private javax.swing.JButton btnAgregarPostal;
    private javax.swing.JButton btnVenderPostal;
    private javax.swing.JButton btnVerAlbum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPrincipal;
    // End of variables declaration//GEN-END:variables
}
